# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32646813030fa1a1c7696b4b7854f2bd71bef68ea76cec07b1b55b6c30954edc59f01cb1ddff2b66fa2554a105f532e1f327694773f233d2b56c9dc033f21988

test:
  secret_key_base: 01dfab60593f1173a7fa47c7874c993b4b333562afe70150ffe11cfdf41c7e6f01953927bbea4b8253182fe8981453a4a4b6091e3a18e6a1b23c0b2c22bc98c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
